### ISSUE TITLE
babel just can't even when transpiling export statement

### ISSUE THREAD

**Issue by cryptoquick** [reactuate/reactuate#19]
I've been trying to get babel-node to run my top-level .jsx file to no avail. I've also tried with a require hook and just node. I'm running v5.5.0.

```
/Users/hunter/GitHub/whatfurry/node_modules/reactuate/src/index.js:1
(function (exports, require, module, __filename, __dirname) { export Application            from './Application'
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at require.extensions.(anonymous function) (/Users/hunter/GitHub/whatfurry/node_modules/babel-register/lib/node.js:136:7)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/hunter/GitHub/whatfurry/node_modules/reactuate/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/hunter/GitHub/whatfurry/node_modules/reactuate/index.js:3:18)
```

**Comment by yrashk** [comment]
Sorry for taking so long. Are you still experiencing this issue?

**Comment by cryptoquick** [comment]
I don't believe I fixed it, but I moved on to a home-rolled stack, learned how to configure webpack, that sort of thing. Thanks for responding though. I'll close the issue.
