### ISSUE TITLE
node 6 problem

### ISSUE THREAD

**Issue by rosenk** [reactuate/reactuate#37]
```
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at /home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
    at Array.map (native)
    at OptionManager.resolvePresets (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/home/rosen/home/dev/reactuate/node_modules/babel-core/lib/transformation/file/index.js:194:75)
```

I believe that the babel-core needs to be upgraded to 6.7.7 in order to work. Also the project is using some older versions like react 15.0.1, etc

[https://github.com/cloverfield-tools/universal-react-boilerplate/pull/100](https://github.com/cloverfield-tools/universal-react-boilerplate/pull/100)

**Comment by yrashk** [comment]
Hi,

Thanks for submitting the issue. I've been spending less time on this project due to changes in priorities, that's why a number of dependencies got outdated.

Would you mind submitting a PR to fix the issue? Will be greatly appreciated!

Yurii.
